version: '3'

services:
  apiZapateriaRenovada:
    image: rubenking23/api_zapateria_renovada
    container_name: api_zapateria_renovada
    networks:
      - net-cloud
    depends_on:
      - postgresRenovada
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresRenovada:5432/complexivo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Nahofumi2001
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_DATASOURCE_CACHEPREPSTMTS=false
    ports:
      - 9094:8080
    restart: always

  postgresRenovada:
    image: postgres:13-renovada
    container_name: postgres_renovada
    networks:
      - net-cloud
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=complexivo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nahofumi2001
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  webZapateriaRenovada:
    image: rubenking23/web_zapateria_renovada
    container_name: web_zapateria_renovada
    networks:
      - net-cloud
    ports:
      - 9096:80
    depends_on:
      - apiZapateriaRenovada
    restart: always

networks:
  net-cloud:

volumes:
  postgres-data:


